apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: microservices-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
        - name: cartservice
          image: bharat5/cartservice:2.0
          ports:
            - containerPort: 7070
          envFrom:
            - configMapRef:
                name: cart-config