{{- range $serviceName, $service := .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $service.name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ $service.name }}
spec:
  replicas: {{ $service.replicaCount }}
  selector:
    matchLabels:
      app: {{ $service.name }}
  template:
    metadata:
      labels:
        app: {{ $service.name }}
    spec:
      containers:
        - name: {{ $service.name }}
          image: "{{ $service.image }}"  
          ports:
            - containerPort: {{ $service.port }}
          env:
            {{- range $service.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
---
{{- end }}
