apiVersion: v1
kind: Service
metadata:
  name: productcatalogservice
  namespace: microservices-demo
spec:
  selector:
    app: productcatalogservice
  ports:
    - protocol: "TCP"
      port: 3550
      targetPort: 3550
  type: ClusterIP
