apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: microservices-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: bharat5/frontend:2.0
        ports:
          - containerPort: 8080
        envFrom:
          - configMapRef:
              name: frontend-config
