apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkoutservice
  namespace: microservices-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkoutservice
  template:
    metadata:
      labels:
        app: checkoutservice
    spec:
      containers:
        - name: checkoutservice
          image: bharat5/checkoutservice:2.0
          ports:
            - containerPort: 5050
          envFrom:
            - configMapRef:
              name: checkout-config