apiVersion: v1
kind: Service
metadata:
  name: checkoutservice
  namespace: microservices-demo
spec:
  selector:
    app: checkoutservice
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
  type: ClusterIP