apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  namespace: microservices-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator
  template:
    metadata:
      labels:
        app: loadgenerator
    spec:
      containers:
      - name: loadgenerator
        image: bharat5/loadgenerator:2.0
        ports:
          - containerPort: 8089
        envFrom:
          - configMapRef:
              name: loadgenerator-config
