apiVersion: v1
kind: Service
metadata:
  name: loadgenerator
  namespace: microservices-demo
spec:
  selector:
    app: loadgenerator
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
  type: ClusterIP
