apiVersion: v1
kind: Service
metadata:
  name: adservice
  namespace: microservices-demo
spec:
  selector:
    app: adservice
  ports:
    - protocol: TCP
      port: 9555
      targetPort: 9555
  type: ClusterIP
