apiVersion: v1
kind: Service
metadata:
  name: paymentservice
  namespace: microservices-demo
spec: 
  selector:
    app: paymentservice
  ports:
  - protocol: TCP
    port: 50051
    targetPort: 50051
  type: ClusterIP