apiVersion: v1
kind: Deployment 
metadata:
  name: recommendationservice
  namespace: microservices-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
    containers:
      - name: recommendationservice
        image: bharat5/recommendendationservice:2.0
        ports:
         - containerPort: 8080
        envFrom:
          - configMapRef:
            name: recommendation-config