apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
  namespace: microservices-demo
spec:
  selector:
    app: recommendationservice
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
