global:
  namespace: "microservices-demo"

services:
  redis:
    name: "redis"
    replicaCount: 1
    image: "redis:alpine"
    port: 6379

  adservice:
    name: "adservice"
    replicaCount: 1
    image: "bharat5/adservice:2.0"
    port: 9555

  cartservice:
    name: "cartservice"
    replicaCount: 1
    image: "bharat5/cartservice:2.0"
    port: 7070
    env:
      - name: PORT
        value: "7070"
      - name: REDIS_ADDR
        value: "redis:6379"
      - name: REDIS_HOST
        value: "redis"

  checkoutservice:
    name: "checkoutservice"
    replicaCount: 1
    image: "bharat5/checkoutservice:2.0"
    port: 5050
    env:
      - name: PORT
        value: "5050"
      - name: CART_SERVICE_ADDR
        value: "cartservice:7070"
      - name: CURRENCY_SERVICE_ADDR
        value: "currencyservice:7000"
      - name: PAYMENT_SERVICE_ADDR
        value: "paymentservice:50051"
      - name: EMAIL_SERVICE_ADDR
        value: "emailservice:8080"
      - name: SHIPPING_SERVICE_ADDR
        value: "shippingservice:50051"
      - name: PRODUCT_CATALOG_SERVICE_ADDR
        value: "productcatalogservice:3550"

  currencyservice:
    name: "currencyservice"
    replicaCount: 1
    image: "bharat5/currencyservice:2.0"
    port: 7000
    env:
      - name: PORT
        value: "7000"

  frontend:
    name: "frontend"
    replicaCount: 1
    image: "bharat5/frontend:2.0"
    port: 8080
    serviceType: "NodePort"
    env:
      - name: PORT
        value: "8080"
      - name: CHECKOUT_SERVICE_ADDR
        value: "checkoutservice:5050"
      - name: CART_SERVICE_ADDR
        value: "cartservice:7070"
      - name: CURRENCY_SERVICE_ADDR
        value: "currencyservice:7000"
      - name: PAYMENT_SERVICE_ADDR
        value: "paymentservice:50051"
      - name: EMAIL_SERVICE_ADDR
        value: "emailservice:8080"
      - name: SHIPPING_SERVICE_ADDR
        value: "shippingservice:50051"
      - name: PRODUCT_CATALOG_SERVICE_ADDR
        value: "productcatalogservice:3550"
      - name: RECOMMENDATION_SERVICE_ADDR
        value: "recommendationservice:8080"
      - name: AD_SERVICE_ADDR
        value: "adservice:9555"
      - name: SHOPPING_ASSISTANT_SERVICE_ADDR
        value: "shoppingassistantservice:8080"

  loadgenerator:
    name: "loadgenerator"
    replicaCount: 1
    image: "bharat5/loadgenerator:2.0"
    port: 8089
    env:
      - name: PORT
        value: "8089"
      - name: FRONTEND_ADDR
        value: "frontend:8080"
      - name: USERS
        value: "10"

  paymentservice:
    name: "paymentservice"
    replicaCount: 1
    image: "bharat5/paymentservice:2.0"
    port: 50051
    env:
      - name: PORT
        value: "50051"

  productcatalogservice:
    name: "productcatalogservice"
    replicaCount: 1
    image: "bharat5/productcatalogservice:2.0"
    port: 3550
    env:
      - name: PORT
        value: "3550"
      - name: DISABLE_PROFILING
        value: "true"

  recommendationservice:
    name: "recommendationservice"
    replicaCount: 1
    image: "bharat5/recommendationservice:2.0"
    port: 8080
    env:
      - name: PORT
        value: "8080"
      - name: PRODUCT_CATALOG_SERVICE_ADDR
        value: "productcatalogservice:3550"

  shippingservice:
    name: "shippingservice"
    replicaCount: 1
    image: "bharat5/shippingservice:2.0"
    port: 50051
    env:
      - name: PORT
        value: "50051"

  emailservice:
    name: "emailservice"
    replicaCount: 1
    image: "bharat5/emailservice:2.0"
    port: 8080
    env:
      - name: PORT
        value: "8080"

  shoppingassistantservice:
    name: "shoppingassistantservice"
    replicaCount: 1
    image: "bharat5/shoppingassistantservice:2.0"
    port: 8080
    env:
      - name: PORT
        value: "8080"
