apiVersion: v1
kind: Deployment
metadata:
  name: emailservice
  namespace: microservices-demo
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: emailservice
    template:
      metadata:
        labels:
          app: emailservice
      spec:
        containers:
        - name: emailservice
          image: bharat5/emailservice:2.0
          ports:
          - containerPort: 8080
          envFrom:
            - configMapRef:
                name: email-config