apiVersion: v1
kind: Service
metadata:
  name: currencyservice
  namespace: microservices-demo
spec:
  selector:
    app: currencyservice
  ports:
    - protocol: TCP
      port: 7000
      targetPort: 7000
  type: ClusterIP
