apiVersion: v1
kind: Service
metadata:
  name: shoppingassistantservice
  namespace: microservices-demo
spec:
  selector:
    app: shoppingassistantservice
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: ClusterIP
