name: Build and Push Docker Images

on:
  push:
    paths:
      - 'docker/**' # Only trigger on Dockerfile changes

    branches:
      - main  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Microservices Images
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/cartservice:2.0 -f docker/cartservice.Dockerfile .
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:2.0 -f docker/frontend.Dockerfile .
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/currencyservice:2.0 -f docker/currencyservice.Dockerfile .
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/paymentservice:2.0 -f docker/paymentservice.Dockerfile .
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/emailservice:2.0 -f docker/emailservice.Dockerfile .
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/checkoutservice:2.0 -f docker/checkoutservice.Dockerfile .
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/productcatalogservice:2.0 -f docker/productcatalog.Dockerfile .
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/shippingservice:2.0 -f docker/shippingservice.Dockerfile .
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/recommendationservice:2.0 -f docker/recommendation.Dockerfile .
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/adservice:2.0 -f docker/adservice.Dockerfile .
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/shoppingassistantservice:2.0 -f docker/shoppingassistant.Dockerfile .
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/loadgenerator:2.0 -f docker/loadgenerator.Dockerfile .

          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/cartservice:2.0
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/frontend:2.0
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/currencyservice:2.0
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/paymentservice:2.0
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/emailservice:2.0
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/checkoutservice:2.0
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/productcatalogservice:2.0
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/shippingservice:2.0
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/recommendationservice:2.0
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/adservice:2.0
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/shoppingassistantservice:2.0
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/loadgenerator:2.0
          
